

include(FindPackageHandleStandardArgs)

message(STATUS "Conan: Using autogenerated FindZLIB.cmake")
# Global approach
set(ZLIB_FOUND 1)
set(ZLIB_VERSION "1.2.11")

find_package_handle_standard_args(ZLIB REQUIRED_VARS ZLIB_VERSION VERSION_VAR ZLIB_VERSION)
mark_as_advanced(ZLIB_FOUND ZLIB_VERSION)



set(ZLIB_INCLUDE_DIRS "/root/.conan/data/zlib/1.2.11/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/include")
set(ZLIB_INCLUDE_DIR "/root/.conan/data/zlib/1.2.11/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/include")
set(ZLIB_INCLUDES "/root/.conan/data/zlib/1.2.11/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/include")
set(ZLIB_RES_DIRS )
set(ZLIB_DEFINITIONS )
set(ZLIB_LINKER_FLAGS_LIST "" "")
set(ZLIB_COMPILE_DEFINITIONS )
set(ZLIB_COMPILE_OPTIONS_LIST "" "")
set(ZLIB_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(ZLIB_LIBRARIES "") # Will be filled later
set(ZLIB_LIBS "") # Same as ZLIB_LIBRARIES
set(ZLIB_SYSTEM_LIBS )
set(ZLIB_FRAMEWORK_DIRS )
set(ZLIB_FRAMEWORKS )
set(ZLIB_FRAMEWORKS_FOUND "") # Will be filled later
set(ZLIB_BUILD_MODULES_PATHS )

# Apple frameworks
if(APPLE)
    foreach(_FRAMEWORK ${ZLIB_FRAMEWORKS})
        # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
        find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${ZLIB_FRAMEWORK_DIRS})
        if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
            list(APPEND ZLIB_FRAMEWORKS_FOUND ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
        else()
            message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${ZLIB_FRAMEWORK_DIRS}")
        endif()
    endforeach()
endif()

mark_as_advanced(ZLIB_INCLUDE_DIRS
                 ZLIB_INCLUDE_DIR
                 ZLIB_INCLUDES
                 ZLIB_DEFINITIONS
                 ZLIB_LINKER_FLAGS_LIST
                 ZLIB_COMPILE_DEFINITIONS
                 ZLIB_COMPILE_OPTIONS_LIST
                 ZLIB_LIBRARIES
                 ZLIB_LIBS
                 ZLIB_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to ZLIB_LIBS and ZLIB_LIBRARY_LIST
set(ZLIB_LIBRARY_LIST z)
set(ZLIB_LIB_DIRS "/root/.conan/data/zlib/1.2.11/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/lib")
foreach(_LIBRARY_NAME ${ZLIB_LIBRARY_LIST})
    unset(CONAN_FOUND_LIBRARY CACHE)
    find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${ZLIB_LIB_DIRS}
                 NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
    if(CONAN_FOUND_LIBRARY)
        list(APPEND ZLIB_LIBRARIES ${CONAN_FOUND_LIBRARY})
        if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
            # Create a micro-target for each lib/a found
            set(_LIB_NAME CONAN_LIB::ZLIB_${_LIBRARY_NAME})
            if(NOT TARGET ${_LIB_NAME})
                # Create a micro-target for each lib/a found
                add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
            else()
                message(STATUS "Skipping already existing target: ${_LIB_NAME}")
            endif()
            list(APPEND ZLIB_LIBRARIES_TARGETS ${_LIB_NAME})
        endif()
        message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
    else()
        message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
        list(APPEND ZLIB_LIBRARIES_TARGETS ${_LIBRARY_NAME})
        list(APPEND ZLIB_LIBRARIES ${_LIBRARY_NAME})
    endif()
endforeach()
set(ZLIB_LIBS ${ZLIB_LIBRARIES})

foreach(_FRAMEWORK ${ZLIB_FRAMEWORKS_FOUND})
    list(APPEND ZLIB_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND ZLIB_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${ZLIB_SYSTEM_LIB})
    list(APPEND ZLIB_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND ZLIB_LIBRARIES ${_SYSTEM_LIB})
endforeach()

set(CMAKE_MODULE_PATH "/root/.conan/data/zlib/1.2.11/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/root/.conan/data/zlib/1.2.11/_/_/package/d50a0d523d98c15bb147b18fa7d203887c38be8b/" ${CMAKE_PREFIX_PATH})

foreach(_BUILD_MODULE_PATH ${ZLIB_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET ZLIB::ZLIB)
        add_library(ZLIB::ZLIB INTERFACE IMPORTED)
        
    if(ZLIB_INCLUDE_DIRS)
      set_target_properties(ZLIB::ZLIB PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${ZLIB_INCLUDE_DIRS}")
    endif()
    set_property(TARGET ZLIB::ZLIB PROPERTY INTERFACE_LINK_LIBRARIES ${ZLIB_LIBRARIES_TARGETS} ${ZLIB_SYSTEM_LIBS} "${ZLIB_LINKER_FLAGS_LIST}")
    set_property(TARGET ZLIB::ZLIB PROPERTY INTERFACE_COMPILE_DEFINITIONS ${ZLIB_COMPILE_DEFINITIONS})
    set_property(TARGET ZLIB::ZLIB PROPERTY INTERFACE_COMPILE_OPTIONS "${ZLIB_COMPILE_OPTIONS_LIST}")

        
    endif()
endif()
